language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

matrix:
    include:
        - php: "hhvm-nightly"
          env:
            - NO_COVERAGE=1
            - BZION_HHVM=1
    allow_failures:
        - php: 5.6
        - php: hhvm-nightly
    fast_finish: true

install:
 - curl -sS https://getcomposer.org/installer | php

before_script: bash -xe tests/initialize.sh

script: tests/runTests.sh

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

notifications:
  webhooks:
    - http://helit.org:8093/+sujevo/showSuccessfulBuildMessages=on_change
    - http://helit.org:8093/++alezakos/showSuccessfulBuildMessages=always
